### ISSUE TITLE
Turn this code into a python package?

### ISSUE THREAD

**Issue by AustinT** [joneswack/dp-rfs#2]
Hello @joneswack, I found this code useful for my own work on random features for graph kernels. Do you have any interest it turning it into an installable python package so that other projects can easily use your implementations of polynomial random features? I would find this useful for a project I am currently working on and would be willing to help with the packaging 😃

**Comment by joneswack** [comment]
Hey Austin! I am very happy that you find my code useful :) I would also be curious to see how you are using it for graph kernels. Right now there is no plan to build a Python package, since I am quite packed with other work I have to do.

For TensorSketch, there exists a CPU implementation in Sci-kit learn in case you haven't seen it:
https://scikit-learn.org/stable/modules/generated/sklearn.kernel_approximation.PolynomialCountSketch.html

A PyTorch package can be found here:
https://github.com/gdlg/pytorch_compact_bilinear_pooling

But it's true that a PyTorch extension with GPU support for all sketches would be nice!

**Comment by AustinT** [comment]
> Right now there is no plan to build a Python package, since I am quite packed with other work I have to do.

Totally understand. Let's just leave this open for the time being then?

> For TensorSketch, there exists a CPU implementation [...]

Thanks for these pointers! My understanding of the count sketch implementations you referenced is that they approximate a polynomial kernel of degree `p` using a naive product of independent count sketches, and not the hierarchical technique suggested by Ahle et al. I presume that the sketches in this repo would achieve lower error in practice for the same number of features. Do you agree with this?

> I would also be curious to see how you are using it for graph kernels.

We used it in our [recent paper](https://arxiv.org/abs/2306.14809) to define a sketch for a kernel which is commonly used in cheminformatics. It represents graphs as sets of subgraphs indexed by a sparse vector. The kernel we use operates on these sparse vectors. Details are in section 4 of our paper. We are working on a revision now.

**Comment by joneswack** [comment]
Very excited to see that these sketches are used for kernels in cheminformatics! What is your degree $p$?

TensorSketch does not use a naive product but a convolution of count sketches. This results in an implicit count sketch of the tensor product of the inputs as shown in my thesis in Section 2.2.2:
https://theses.hal.science/tel-03829604v1/document

The hierarchical algorithm by Ahle et al. only leads to improvements for large $p$, e.g., p>6 in my experiments. So I would say that the major improvements by their method are in terms of theoretical guarantees rather than practical advantages. In case you have a p<6 you can safely go with TensorSketch or use my CtR-ProductSRHT method (https://arxiv.org/pdf/2202.02031.pdf) that performs a bit better, but is not implemented in a Python package. If you are working with sparse data, count sketch based methods are extremely fast.

**Comment by AustinT** [comment]
> What is your degree p? [...] The hierarchical algorithm by Ahle et al. only leads to improvements for large p, e.g., p>6 in my experiments.

The sketch proposed in my paper uses a truncated power series representation of the kernel. In principle it is desirable for p to be as large as possible, but in practice we only considered p<=5. Maybe this means naive CountSketch is enough.

Overall I think I will try the scikit learn version and see how it performs. If I want to use code from this repo I will just copy the bits I need and use an Apache License (to respect the terms of the Apache license of this repo). Thanks so much for the guidance!

**Comment by AustinT** [comment]
(closing because it looks like this won't be turned into a python package at this time)
